[package]
name = "caesar_cipher_enc_dec"
version = "0.4.0"
edition = "2021"
description = "can easily use caesar cipher"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
